config/routes.rb
Portal::Application.routes.draw do
  devise_for :users

  resources :contacts

  get "home/index"

  root :to => 'home#index'
  match ':controller(/:action(/:id))(.:format)'

  
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  attr_accessible :email, :message, :name, :subject, :source
  validates :name, :presence => {:message => "required"}
  validates :email,:presence => {:message => "required"} 
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, on: :create }
  validates :subject,:presence => {:message => "required"} 
  validates :message,:presence => {:message => "required"}

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @contacts }
    end
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
    @contact = Contact.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @contact }
    end
  end

  # GET /contacts/new
  # GET /contacts/new.json
  def new
    @contact = Contact.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @contact }
    end
  end

  # GET /contacts/1/edit
  def edit
    @contact = Contact.find(params[:id])
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(params[:contact])

    respond_to do |format|
      if @contact.save
        UserMailer.contact_email(@contact).deliver
        flash[:notice] = 'Thanks for contacting us. We will be in touch shortly!'
        format.html { redirect_to :controller => 'home', :action =>"index" }  #
        format.json { render json: @contact, status: :created, location: @contact }
      else
        format.html { redirect_to :controller => 'home', :action =>"index", :anchor =>"contact", :errors => @contact.errors.full_messages}
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /contacts/1
  # PUT /contacts/1.json
  def update
    @contact = Contact.find(params[:id])

    respond_to do |format|
      if @contact.update_attributes(params[:contact])
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact = Contact.find(params[:id])
    @contact.destroy

    respond_to do |format|
      format.html { redirect_to contacts_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@contact = Contact.new if !defined? @contact #automatically create a contact variable 
  end

  def create_contact_from_form
    @contact = Contact.new(params[:contact])

    respond_to do |format|
      if @contact.save
        format.html { redirect_to home_url , notice: 'Thanks for the Message!' } #
      else
        format.html { redirect_to home_url}
      end
    end
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return "" if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join

    html = <<-HTML
    <div id="error_explanation">
      <ul>#{messages}</ul>
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/contacts/_form.html.erb
<%= form_for(@contact) do |f| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% @contact.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :subject %><br />
    <%= f.text_field :subject %>
  </div>
  <div class="field">
    <%= f.label :message %><br />
    <%= f.text_field :message %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing contact</h1>

<%= render 'form' %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<h1>Listing contacts</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Subject</th>
    <th>Message</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @contacts.each do |contact| %>
  <tr>
    <td><%= contact.name %></td>
    <td><%= contact.email %></td>
    <td><%= contact.subject %></td>
    <td><%= contact.message %></td>
    <td><%= link_to 'Show', contact %></td>
    <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
    <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Contact', new_contact_path %>

app/views/contacts/new.html.erb
<h1>New contact</h1>

<%= render 'form' %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<p>
  <b>Name:</b>
  <%= @contact.name %>
</p>

<p>
  <b>Email:</b>
  <%= @contact.email %>
</p>

<p>
  <b>Subject:</b>
  <%= @contact.subject %>
</p>

<p>
  <b>Message:</b>
  <%= @contact.message %>
</p>


<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

app/views/home/index.html.erb
<a href="#top" id="toTop" class="icon fa-arrow-up"></a>
	<!-- Home -->
		<div class="wrapper style1 first">
			<article class="container" id="top">
				<div class="row">
					<div class="4u">
						<span class="image fit"><%=image_tag("front-image.jpg" , :alt => "Imajine Software") %></span>
					</div>
					<div class="8u">
						<header>
							<h1>We are <strong>Imajine</strong>.</h1>
						</header>
						<p style="text-align:left;">A web development and software company located in the <strong>Washington D.C.</strong> area serving all of the United States. </p>
						<a href="#work" class="button big scrolly">Learn About Our Services</a>
					</div>
				</div>
			</article>
		</div>

	<!-- Work -->
		<div class="wrapper style2">
			<article id="work">
				<header>
					<h2 class="web-services">Web Sites</h2>
				</header>
				<div class="container services-container">
					<div class="row">
						<div class="4u">
							<section class="box style1">
								<span class="icon featured web-services fa-laptop"></span>
								<h3 class="web-services">Web Applications</h3>
								<p>Custom web applications that support user login, social networking, and any features tailored to your business.</p>
							</section>
						</div>
						<div class="4u">
							<section class="box style1">
								<span class="icon featured web-services fa-wordpress"></span>
								<h3 class="web-services">Web Design</h3>
								<p>Modern Web-Design using the highest quality logos, layout, fonts. We also build custom Wordpress themes.</p>
							</section>
						</div>
						<div class="4u">
							<section class="box style1">
								<span class="icon featured web-services fa-cc-visa"></span>
								<h3 class="web-services">E-Commerce</h3>
								<p>Accept customer payments using Stripe, Square, Authorize, Paypal, and many other payment processors.</p>
							</section>
						</div>
					</div>
				</div>
				<header>
					<h2 class="mobile-services">Mobile Apps</h2>
				</header>
				<div class="container services-container">
					<div class="row">
						<div class="4u">
							<section class="box style1">
								<span class="icon featured mobile-services fa-apple"></span>
								<h3 class="mobile-services">Iphone/Ipad Apps</h3>
								<p>We build amazing, scale-able Iphone Apps for the just released IOS8 platform and earlier OS's. </p>
							</section>
						</div>
						<div class="4u">
							<section class="box style1">
								<span class="icon featured  mobile-services fa-android"></span>
								<h3 class="mobile-services">Android Apps</h3>
								<p>Androids apps you ask? Yes high quality, stylish ones for the Google Play Marketplace!</p>
							</section>
						</div>
						<div class="4u">
							<section class="box style1">
								<span class="icon featured mobile-services fa-tablet"></span>
								<h3 class="mobile-services">Mobile Layout</h3>
								<p>Mobile app not right for you? We can build a website that looks and feels like a mobile app.</p>
							</section>
						</div>
					</div>
				</div>
				<header>
					<h2 class="advertising-services">Web Advertising</h2>
				</header>
				<div class="container services-container">
					<div class="row">
						<div class="4u">
							<section class="box style1">
								<span class="icon featured advertising-services fa-thumbs-o-up"></span>
								<h3 class="advertising-services">Social Media</h3>
								<p>Our team can create social media (facebook, twitter, etc) pages for you and run ad campaigns.</p>
							</section>
						</div>
						<div class="4u">
							<section class="box style1">
								<span class="icon featured advertising-services fa-yelp"></span>
								<h3 class="advertising-services">Yelp Campaigns</h3>
								<p>Want to expand locally? We run yelp campaigns centered on coupons to help attract local customers.</p>
							</section>
						</div>
						<div class="4u">
							<section class="box style1">
								<span class="icon featured advertising-services fa-google"></span>
								<h3 class="advertising-services">Search Advertising</h3>
								<p>We create & manage ads that target Google search engine keywords. For example - "lawyer Washington D.C."</p>
							</section>
						</div>
					</div>
				</div>
				<footer>
					<p>Do we have samples of our recent work you ask?</p>
					<a href="#portfolio" class="button big scrolly">Check Out Recent Projects!</a>
				</footer>
			</article>
		</div>
	<!-- Portfolio -->
		<div class="wrapper style3">
			<article id="portfolio">
				<header>
					<h2>Here’s what our team has been working on. </h2>
				</header>
				<div class="container">
					<div class="row">
						<div class="6u">
							<article class="box style2">
								<%=link_to image_tag("scholar-law.png",:alt =>"Scholar Law"), "http://www.scholarlaw.net",  :class =>"image featured" %>
								<h3><a href="http://www.scholarlaw.net">Scholar Law</a></h3>
								<p>A website for a lawyer located in Falls Church, VA.</p>
							</article>
						</div>
						<div class="6u">
							<article class="box style2">
								<%=link_to image_tag("fsm50.png",:alt =>"FSM50"), "http://www.fsm50.com",  :class =>"image featured" %>
								<h3><a href="http://www.fsm50.com">FSM50</a></h3>
								<p>A web app to organize members of the Free Speech Movement. </p>
							</article>
						</div>
					</div>
					<div class="row">
						<div class="6u">
							<article class="box style2">
								<%=link_to image_tag("focusd.png",:alt =>"focusd"), "http://focusd.info", :class =>"image featured" %>
								<h3><a href="http://focusd.info">Focusd App - Android</a></h3>
								<p>A landing page for the Focusd Android App.</p>
							</article>
						</div>
						<div class="6u">
							<article class="box style2">
								<%=link_to image_tag("24hrclockworks.png",:alt =>"24hrclockworks"), "http://www.24hrclockworks.com", :class =>"image featured" %>
								<h3><a href="http://www.24hrclockworks.com">24hrclockworks</a></h3>
								<p>A web-site for a top-notch clock repairsman in Arlington,VA.</p>
							</article>
						</div>
					</div>
					<div class="row">
						<div class="6u">
							<article class="box style2">
								<%=link_to image_tag("linder.png",:alt =>"Linder"), "http://www.linkedin.com",  :class =>"image featured" %>
								<h3><a href="http://www.linkedin.com">Linder IOS App - Coming Soon</a></h3>
								<p>An IOS 8 app to help organize the members of LinkedIn.</p>
							</article>
						</div>
						<div class="6u">
							<article class="box style2">
								<%=link_to image_tag("yelp-24hrclockworks.png",:alt =>"24hrclockworks"), "hhttp://www.yelp.com/biz/24-hr-watch-and-clockworks-arlington",  :class =>"image featured" %>
								<h3><a href="http://www.yelp.com/biz/24-hr-watch-and-clockworks-arlington">24hrclockworks Yelp Campaign</a></h3>
								<p>Creating and Managing the Yelp of 24hrclockworks.</p>
							</article>
						</div>
					</div>
				</div>
				<footer>
					<p>Have a project you need help with or general question?</p>
					<a href="#contact" class="button big scrolly">Get in touch with us</a>
				</footer>
			</article>
		</div>

	<!-- Contact -->
		<div class="wrapper style4">
			<article id="contact" class="container small">
				<header>
					<h2>Contact us.</h2>
					<p>If we don't get back to you within 24 hours that's an automatic <strong style="color:#3BDD77">15% discount.</strong> </p>
				</header>
				<div>
					<% unless params[:errors].nil?  %> <!-- errors set by flash in contacts_controller -->
					<div class="errors">
						<h4>Please correct the following:</h4>
						<% params[:errors].each do |msg| %>
							<%= msg %>
							<br>
						<% end %>
						</div>
						<% end %>

					<div class="row">
						<div class="12u">
							<%= form_for(@contact) do |f| %> 
								<div>
								  	<div class="row"> 
										<div class="field 6u">
											<%= f.text_field :name, {:placeholder=> "Name *"} %>
										</div>
										<div class="field 6u">
											<%= f.text_field :email, {:placeholder=> "Email *"} %>
										</div>
									</div>
								   	<div class="row"> 
								    	<div class="field 12u">
								    	<%= f.text_field :subject , {:placeholder=> "Subject *"} %>
								  		</div>
							  		</div>
								   	<div class="row"> 
								    	<div class="field 12u">
								    	<%= f.text_area :message , {:placeholder=> "Message *"} %>
								  		</div>
							  		</div>
							  		<div class="row">
							    		<%= f.hidden_field :source, :value => "From Contact Form" %>
							    	</div>
									<div class="row double">
										<div class="12u">
											<ul class="actions">
												<li><%=f.submit "Send Message", :class => "contact-button" %></li>
												<li><input type="reset" value="Clear Form" class="alt" /></li>
											</ul>
										</div>
									</div>
								</div>
								<% end %>
						</div>
					</div>
				</div>
			</article>
		</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Imajine | Webdesign | Iphone Apps</title>
	<!--[if lte IE 8]><%=javascript_include_tag "html5shiv" %><![endif]-->
	<%= javascript_include_tag "application" %>
	<%= stylesheet_link_tag    "application", :media => "all" %>
	<%= stylesheet_link_tag    "home", :media => "all" %>
	<!--[if lte IE 8]> <%= stylesheet_link_tag    "v8", :media => "all" %><![endif]-->
	<!--[if lte IE 9]><%= stylesheet_link_tag    "v9", :media => "all" %><![endif]-->

  <%= csrf_meta_tags %>
</head>
<body>
	<div id="notice" class="centered">
		<% unless notice.nil? %>
		<p class="notice" style="margin:0px;"> <%= notice %></p>
		<% end %>
		<% unless alert.nil? %>
	    <p class="alert"><%= alert %></p>
		<% end %>
	</div>
		<!-- Nav -->
			<nav id="nav">
				<ul class="container">
					<li><a href="http://imajine.us#top">Home</a></li>
					<li><a href="http://imajine.us#work">Work</a></li>
					<li><a href="http://imajine.us#portfolio">Portfolio</a></li>
					<li><a href="http://imajine.us#contact">Contact</a></li>
					<% if user_signed_in? %>
					 <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
					<% else %>
					<li> <%= link_to("Client Portal ",:controller => "users", :action => "sign_in")%></li>
					<% end %>
				</ul>
			</nav>
	<%= yield %>
	<div class="footer-wrapper">
		<div class="row">
			<div class="12u">
				<hr />
				<h3>Find us on ...</h3>
				<ul class="social">
					<li><a href="#" class="icon fa-twitter"><span class="label">Twitter</span></a></li>
					<li><a href="#" class="icon fa-linkedin"><span class="label">LinkedIn</span></a></li>
					<li><a href="#" class="icon fa-github"><span class="label">Github</span></a></li>
					<!--
					<li><a href="#" class="icon fa-rss"><span>RSS</span></a></li>
					<li><a href="#" class="icon fa-instagram"><span>Instagram</span></a></li>
					<li><a href="#" class="icon fa-foursquare"><span>Foursquare</span></a></li>
					<li><a href="#" class="icon fa-skype"><span>Skype</span></a></li>
					<li><a href="#" class="icon fa-soundcloud"><span>Soundcloud</span></a></li>
					<li><a href="#" class="icon fa-youtube"><span>YouTube</span></a></li>
					<li><a href="#" class="icon fa-blogger"><span>Blogger</span></a></li>
					<li><a href="#" class="icon fa-flickr"><span>Flickr</span></a></li>
					<li><a href="#" class="icon fa-vimeo"><span>Vimeo</span></a></li>
					-->
				</ul>
				<hr />
			</div>
		</div>
		<footer>
			<ul id="copyright">
				<li>&copy; Imajine. All rights reserved.</li><li>Design: <a href="http://html5up.net">HTML5 UP</a></li>
			</ul>
		<script type="text/javascript">
			$(function() {
				$("#toTop").scrollToTop();
				  $( "#notice" ).fadeOut( 3500, function() {
					});
			});
		</script>
		</footer>
	</div>
</body>
</html>

app/views/shared/_flash_message.html.erb
<% flash.each do |key, value| %>
  <%= content_tag :div, value, class: "flash #{key}" %>
<% end %>